// <auto-generated />
namespace Elisab.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _20190911Section : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190911Section));
        
        string IMigrationMetadata.Id
        {
            get { return "201909110713328_20190911-Section"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
