// <auto-generated />
namespace Elisab.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _20191007CountDownPage_TB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191007CountDownPage_TB));
        
        string IMigrationMetadata.Id
        {
            get { return "201910070734446_20191007-CountDownPage_TB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
