// <auto-generated />
namespace Elisab.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _201909055 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201909055));
        
        string IMigrationMetadata.Id
        {
            get { return "201909051051090_20190905-5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
