// <auto-generated />
namespace Elisab.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _09042019_FashionShow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09042019_FashionShow));
        
        string IMigrationMetadata.Id
        {
            get { return "201909041340025_09042019_FashionShow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
